name: pica_crawler

on:
  # schedule:
  #   - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    paths:
      - '**.py'
      - '**.yml'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      # - name: install dependency
      #   run: |
      #     pip install urllib3
      #     pip install requests
      - name: main logic and install dependency
        env:
          PICA_SECRET_KEY: ${{secrets.PICA_SECRET_KEY}}
          PICA_ACCOUNT: ${{secrets.PICA_ACCOUNT}}
          PICA_PASSWORD: ${{secrets.PICA_PASSWORD}}
          # 过滤分区 用,分隔
          CATEGORIES: 偽娘哲學,扶他樂園,性轉換
          # CATEGORIES_RULE 过滤规则    INCLUDE: 包含任意一个分区就下载  EXCLUDE: 包含任意一个分区就不下载
          CATEGORIES_RULE: INCLUDE
          # 订阅的关键词,会下载x天范围内上传的漫画    为空则关闭关键词订阅 用,分隔
          SUBSCRIBE_KEYWORD: ノードラッグハイテンション(水乃カルキ),ふずめ,谷口さん
          # 订阅的x天范围     git actions运行时填小一点,免得漫画过多邮箱推送不了,本地运行时随便填
          SUBSCRIBE_DAYS: 9000
        run: |
          pip install --upgrade pip
          pip install urllib3
          pip install requests
          python main.py
          git add downl.txt
          7z a -r "comics/finder-result.zip" "comics/*"
      - name: Create timestamp
        id: create_timestamp
        run: echo "::set-output name=timestamp::$(date '+%Y%m%d%H%M%s')"
        shell: bash
      # - name: Get the current branch name
      #   shell: bash
      #   run: echo "##[set-output name=branch;]${GITHUB_REF#refs/heads/}"
      #   id: myref

      # - name: upload-artifact
      #   uses: actions/upload-artifact@v3.1.0
      #   with:
      #     name: pica-comics
      #     path: comics/
      #     retention-days: 2

      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: Auto-${{ steps.myref.outputs.branch }}-dev
      #     release_name: Release1
      #     files: comics/finder-result.zip
      #     draft: false
      #     prerelease: true 

      - name: 自动释放
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "1"
          prerelease: true
          title: "finder-result"
          files: |
           comics/finder-result.zip

      - name: commit & push
        uses: actions-go/push@master
        with:
          author-email: 'actions@github.com'
          author-name: 'GitHub Actions'
          commit-message: '更新下载的漫画'
          token: ${{ secrets.GIT_TOKEN }}
